image: docker:latest

variables:
  DOCKER_DRIVER: overlay
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_REPO_USER: gitlab-ci-token
  
stages:
  - docker
# Currently building SLS+AWS image only
docker-build:
  stage: docker
  services:
    - docker:dind
  script:
    - docker version
    - docker login -u ${DOCKER_REPO_USER} -p $CI_BUILD_TOKEN registry.gitlab.com
    - export IMAGE_NAME=${CI_REGISTRY_IMAGE}:latest
    - docker build -t ${IMAGE_NAME} .
    - docker push ${IMAGE_NAME}
    - export PARENT_IMAGE=${IMAGE_NAME}
    - cd sls_aws
    - export IMAGE_NAME=${CI_REGISTRY_IMAGE}_aws:latest
    - docker build -t ${IMAGE_NAME} --build-arg parent_image=${PARENT_IMAGE} .
    - docker push ${IMAGE_NAME}
 only:
   - main

